### PR TITLE
Switched to Gradle with subprojects

### PR DESCRIPTION
**Pull request by johnzeringue**
Switched to Gradle with subprojects in preparation for the introduction
of web services. `./gradlew test` runs tests. `./gradlew fatJar` builds
a fat JAR in `app/build/libs/` (suffixed `-all`). `./gradlew app:run`
runs the application.

### CODE REVIEW

**Comment by bowring** [comment]
Bound to happen!

However, I am having a time getting Netbeans to load it, even with a clean clone.  Command line gradle works.  @johnzeringue can you investigate?  Thanks.

**Comment by johnzeringue** [comment]
Have you installed the “Gradle Support" plugin?

**Comment by johnzeringue** [comment]
Okay, I've got it going myself in a relatively fresh install of Netbeans 8.1. Here's what I did:

1. Install the "Gradle Support" plugin and restart Netbeans when prompted.
2. Reload project.
3. Open and select the `app` subproject.
4. Press the "Run" button.

At this point, I've got the GUI running.

**Comment by bowring** [comment]
All set.  Netbeans was polluted.  Thanks.

**Pull request merged**
